version: "3.8"

services:
  mysqldb:
    image: mysql:8.2.0 
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_DATABASE=event_db 
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  sonarqube:
    image: sonarqube:8.9.7-community
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9092:9092
    volumes:
      - 'SonarQube_data:/opt/SonarQube/data'
      - 'SonarQube_extensions:/opt/SonarQube/extensions'
      - 'SonarQube_logs:/opt/SonarQube/logs'

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  db:
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_logs:
  prometheus_data:
  grafana_data: